// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBodls_XjKE-rhm1rz9bjhtQcdST3zP7DQ',
    appId: '1:643096193539:web:2fae1214b87acffbaabc36',
    messagingSenderId: '643096193539',
    projectId: 'lasttry-19c31',
    authDomain: 'lasttry-19c31.firebaseapp.com',
    storageBucket: 'lasttry-19c31.appspot.com',
    measurementId: 'G-3881D96YY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavvDjgKXLMj329CL2ve_Cm2ZJu2G2YVw',
    appId: '1:643096193539:android:348dfd0fd57add6caabc36',
    messagingSenderId: '643096193539',
    projectId: 'lasttry-19c31',
    storageBucket: 'lasttry-19c31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbEBJ2X-p_vBCXqLhBheKWmN8KUpxlccw',
    appId: '1:643096193539:ios:5a49248635ae77deaabc36',
    messagingSenderId: '643096193539',
    projectId: 'lasttry-19c31',
    storageBucket: 'lasttry-19c31.appspot.com',
    iosClientId: '643096193539-3h089hett8v3f08qcoo52c9cuucl1rsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.handling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbEBJ2X-p_vBCXqLhBheKWmN8KUpxlccw',
    appId: '1:643096193539:ios:746f74290ea3e73aaabc36',
    messagingSenderId: '643096193539',
    projectId: 'lasttry-19c31',
    storageBucket: 'lasttry-19c31.appspot.com',
    iosClientId: '643096193539-gmlha1rcspt2uc7hdvvreue96k6derd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.handling.RunnerTests',
  );
}
